# Generated by Django 4.2 on 2023-04-10 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ('-created_at',), 'verbose_name': 'Workspace', 'verbose_name_plural': 'Workspaces'},
        ),
    ]
