# Generated by Django 4.1.7 on 2023-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('created_at',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectcolumn',
            options={'ordering': ('created_at',), 'verbose_name': 'Project column', 'verbose_name_plural': 'Project columns'},
        ),
    ]
