# Generated by Django 4.1.7 on 2023-03-28 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        ('Workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposal_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposal', to='Projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_proposal_users', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='project',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='projectcolumn_projects', to='Tasks.projectcolumn', verbose_name='Columns'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_project_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='taskcard_projects', to='Tasks.taskcard', verbose_name='Tasks'),
        ),
        migrations.AddField(
            model_name='project',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='user_project_workers', to=settings.AUTH_USER_MODEL, verbose_name='Workers'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_projects', to='Workspaces.workspace', verbose_name='Workspace'),
        ),
    ]
