# Generated by Django 4.1.7 on 2023-03-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_alter_project_options_alter_projectcolumn_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcolumn',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is private'),
        ),
    ]
