# Generated by Django 4.2 on 2023-04-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='columns',
        ),
    ]
