# Generated by Django 4.1.7 on 2023-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_projectcolumn_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcolumn',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='projectcolumn',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='columns',
            field=models.ManyToManyField(blank=True, null=True, related_name='projectcolumn_project', to='Projects.projectcolumn', verbose_name='Columns'),
        ),
    ]
