# Generated by Django 4.2 on 2023-04-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_remove_project_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_at',), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='proposal',
            options={'ordering': ('-created_at',), 'verbose_name': 'Proposal', 'verbose_name_plural': 'Proposals'},
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
