# Generated by Django 4.1.7 on 2023-03-23 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_projectcolumn_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='columns',
        ),
        migrations.AddField(
            model_name='projectcolumn',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_projectcolumn', to='Projects.project', verbose_name='Project'),
            preserve_default=False,
        ),
    ]
