# Generated by Django 4.1.7 on 2023-03-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0006_remove_project_columns_projectcolumn_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcolumn',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='columns',
            field=models.ManyToManyField(related_name='projectcolumn_project', to='Projects.projectcolumn', verbose_name='Columns'),
        ),
    ]
