# Generated by Django 4.1.7 on 2023-03-24 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Projects', '0009_alter_project_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='columns',
            field=models.ManyToManyField(blank=True, related_name='projectcolumn_projects', to='Projects.projectcolumn', verbose_name='Columns'),
        ),
        migrations.AlterField(
            model_name='projectcolumn',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projectcolumns', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
