# Generated by Django 4.1.7 on 2023-03-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_checklist_item_taskcard_alter_taskcard_creator_and_more'),
        ('Projects', '0010_alter_project_columns_alter_projectcolumn_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='taskcard_projects', to='Tasks.taskcard', verbose_name='Tasks'),
        ),
    ]
