# Generated by Django 4.1.7 on 2023-03-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'is_active')},
        ),
    ]
