# Generated by Django 4.1.7 on 2023-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='field_for_unique',
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
