# Generated by Django 4.1.7 on 2023-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_user_field_for_unique_user_is_private'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
