# Generated by Django 4.1.7 on 2023-03-28 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('number', models.PositiveIntegerField(verbose_name='Serial number')),
            ],
            options={
                'verbose_name': 'Project column',
                'verbose_name_plural': 'Project columns',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectcolumn_taskcards', to='Tasks.projectcolumn', verbose_name='Column')),
            ],
            options={
                'verbose_name': 'TaskCard',
                'verbose_name_plural': 'TaskCards',
                'ordering': ('created_at',),
            },
        ),
    ]
