# Generated by Django 4.1.7 on 2023-03-18 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_taskcard', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'TaskCard',
                'verbose_name_plural': 'TaskCards',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CheckList_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('done', models.BooleanField(default=False, verbose_name='Done')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_checklistitem', to=settings.AUTH_USER_MODEL, verbose_name='Executor')),
                ('taskcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskcard_checklistitem', to='Tasks.taskcard', verbose_name='TaskCard')),
            ],
            options={
                'verbose_name': 'CheckList_item',
                'verbose_name_plural': 'CheckList_items',
                'ordering': ['updated_at'],
            },
        ),
    ]
