# Generated by Django 4.2 on 2023-06-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='colomn',
            new_name='column',
        ),
    ]
