# Generated by Django 4.1.7 on 2023-03-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist_item',
            options={'ordering': ('updated_at',), 'verbose_name': 'CheckList_item', 'verbose_name_plural': 'CheckList_items'},
        ),
        migrations.AlterModelOptions(
            name='taskcard',
            options={'ordering': ('created_at',), 'verbose_name': 'TaskCard', 'verbose_name_plural': 'TaskCards'},
        ),
    ]
