# Generated by Django 4.2 on 2023-06-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_rename_colomn_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Color'),
        ),
    ]
