# Generated by Django 4.1.7 on 2023-03-24 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tasks', '0002_alter_checklist_item_options_alter_taskcard_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_item',
            name='taskcard',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taskcard_checklistitems', to='Tasks.taskcard', verbose_name='TaskCard'),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_taskcards', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
