# Generated by Django 4.2 on 2023-06-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_alter_task_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='column',
            field=models.CharField(choices=[('To Do', 'To Do'), ('In Progress', 'In Progress'), ('In Review', 'In Review'), ('Done', 'Done'), ('Archive', 'Archive')], default='To Do', max_length=30, verbose_name='Column'),
        ),
    ]
