# Generated by Django 4.2 on 2023-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_remove_project_columns'),
        ('Tasks', '0003_alter_taskcard_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='column',
            field=models.CharField(choices=[('ToDO', 'To do'), ('InProgress', 'In progress'), ('ToReview', 'To review'), ('Done', 'Done')], default='To do', max_length=10),
        ),
        migrations.DeleteModel(
            name='ProjectColumn',
        ),
    ]
