# Generated by Django 4.2 on 2023-06-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_alter_member_role'),
        ('Tasks', '0004_alter_task_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.member', verbose_name='Worker'),
        ),
    ]
