# Generated by Django 4.2 on 2023-04-11 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0005_alter_taskcard_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcard',
            name='column',
            field=models.CharField(choices=[('ToDo', 'To do'), ('InProgress', 'In progress'), ('ToReview', 'To review'), ('Done', 'Done')], default='To do', max_length=10),
        ),
    ]
