# Generated by Django 4.2 on 2023-04-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_alter_taskcard_column'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcard',
            options={'ordering': ('-created_at',), 'verbose_name': 'TaskCard', 'verbose_name_plural': 'TaskCards'},
        ),
        migrations.AlterField(
            model_name='taskcard',
            name='column',
            field=models.CharField(choices=[('ToDo', 'To do'), ('InProgress', 'In progress'), ('ToReview', 'To review'), ('Done', 'Done')], default='ToDo', max_length=10),
        ),
    ]
