# Generated by Django 4.2 on 2023-06-11 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0003_alter_member_role'),
        ('Tasks', '0006_task_close'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='worker',
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(blank=True, related_name='member_tasks', to='Members.member', verbose_name='Worker'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End at')),
                ('close', models.BooleanField(default=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_taskitems', to='Members.member', verbose_name='Worker')),
            ],
            options={
                'verbose_name': 'TaskItem',
                'verbose_name_plural': 'TaskItems',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_items',
            field=models.ManyToManyField(blank=True, related_name='taskitems_tasks', to='Tasks.taskitem', verbose_name='Task items'),
        ),
    ]
