# Generated by Django 4.2 on 2023-06-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_remove_task_worker_task_workers_taskitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_items',
            field=models.ManyToManyField(blank=True, related_name='taskitem_tasks', to='Tasks.taskitem', verbose_name='Task items'),
        ),
    ]
