# Generated by Django 4.2 on 2023-06-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_alter_task_task_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='close',
            field=models.BooleanField(default=False),
        ),
    ]
