# Generated by Django 4.2 on 2023-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proposals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='role',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Design', 'Design'), ('Stakeholder', 'Stakeholder'), ('UX', 'UX'), ('Project owner', 'Project owner')], default=1, max_length=20, verbose_name='Role'),
            preserve_default=False,
        ),
    ]
