# Generated by Django 4.2 on 2023-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('is_private', models.BooleanField(default=False, verbose_name='Is private')),
                ('is_scrum', models.BooleanField(default=True, verbose_name='Is scrum')),
            ],
            options={
                'verbose_name': 'ScrumProject',
                'verbose_name_plural': 'ScrumProjects',
                'ordering': ('-created_at',),
            },
        ),
    ]
