# Generated by Django 4.2 on 2023-05-24 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Members', '0002_initial'),
        ('ScrumProjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumproject',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scrumproject_creators', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='scrumproject',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, related_name='member_scrumprojects', to='Members.member', verbose_name='Team'),
        ),
    ]
