# Generated by Django 4.2 on 2023-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_initial'),
        ('ScrumProjects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumproject',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='member_scrumprojects', to='Members.member', verbose_name='Team'),
        ),
    ]
