# Generated by Django 4.2 on 2023-05-29 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ScrumProjects', '0003_alter_scrumproject_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumproject',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scrumproject', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
