# Generated by Django 4.2 on 2023-05-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumProjects', '0004_alter_scrumproject_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumproject',
            name='is_scrum',
        ),
    ]
