# Generated by Django 4.2 on 2023-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backlogs', '0001_initial'),
        ('ScrumProjects', '0005_remove_scrumproject_is_scrum'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumproject',
            name='backlogs',
            field=models.ManyToManyField(blank=True, related_name='backlog_scrumproject', to='Backlogs.backlog', verbose_name='Backlogs'),
        ),
    ]
