# Generated by Django 4.2 on 2023-06-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backlogs', '0001_initial'),
        ('ScrumProjects', '0006_scrumproject_backlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumproject',
            name='backlogs',
            field=models.ManyToManyField(blank=True, related_name='backlog_scrumprojects', to='Backlogs.backlog', verbose_name='Backlogs'),
        ),
    ]
