# Generated by Django 4.2 on 2023-06-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumProjects', '0007_alter_scrumproject_backlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumproject',
            name='backlogs',
        ),
    ]
