# Generated by Django 4.2 on 2023-06-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumProjects', '0008_remove_scrumproject_backlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumproject',
            name='is_scrum',
            field=models.BooleanField(default=True, verbose_name='Is scrum'),
        ),
    ]
