# Generated by Django 4.2 on 2023-06-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sprints', '0002_sprint_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='name',
        ),
    ]
