# Generated by Django 4.2 on 2023-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Design', 'Design'), ('Stakeholder', 'Stakeholder'), ('UX', 'UX'), ('Product owner', 'Product owner')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ('-created_at',),
            },
        ),
    ]
