# Generated by Django 4.2 on 2023-05-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Design', 'Design'), ('Stakeholder', 'Stakeholder'), ('UX', 'UX'), ('Project owner', 'Project owner')], max_length=20),
        ),
    ]
