# Generated by Django 4.2 on 2023-06-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('difficult', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=20)),
                ('start_at', models.DateField(verbose_name='Start at')),
                ('end_at', models.DateField(verbose_name='End at')),
            ],
            options={
                'verbose_name': 'Backlog',
                'verbose_name_plural': 'Backlogs',
                'ordering': ('-created_at',),
            },
        ),
    ]
