# Generated by Django 4.2 on 2023-06-04 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ScrumProjects', '0008_remove_scrumproject_backlogs'),
        ('Backlogs', '0002_remove_backlog_end_at_remove_backlog_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='scrum_project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scrumproject_backlogs', to='ScrumProjects.scrumproject', verbose_name='Scrum project'),
            preserve_default=False,
        ),
    ]
