# Generated by Django 4.2 on 2023-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0001_initial'),
        ('Backlogs', '0003_backlog_scrum_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='task_backlogs', to='Tasks.task', verbose_name='Tasks'),
        ),
    ]
